project:
  type: website

website:
  title: "hymzhao"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: HAHA
      - href: presentations.qmd
        text: Presentations
    right:
      - text: Resume
        href: documents/"Hannah Yimei Zhao Resume 042626.pdf"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

